## 2.1 Tensors and Numpy
<img src="https://firebasestorage.googleapis.com/v0/b/deep-learning-crash-course.appspot.com/o/2Numpy.png?alt=media&token=fc8f3815-66d0-47df-ab28-3d053c42e00e" width="200" height="200" align="right"/>

Tensors 
Mathematically, a tensor is a generalization of vectors and matrices. Within the context of TensorFlow, a tensor is considered as a multi-dimensional array.

With the use of .numpy() method, tensors can be explicilty converted to Numpy ndarrays objects into tf.Tensor objects.

Similar to Numpy ndarray objects, tf.Tensor objects have a data type and a shape. Their mathematical operations are also similar to each other.

Unlike Numpy arrays, tf.Tensors can be backed by accelerator memory (GPU, TPU).

TensorFlow offers a rich library of operations that consume and produce tf.Tensors, such as tf.add, tf.matmul, and tf.linalg.inv. These operations automatically convert native Python types

<img src="https://firebasestorage.googleapis.com/v0/b/deep-learning-crash-course.appspot.com/o/2NumpyDimension.png?alt=media&token=07ff02d0-2499-40ff-b5de-46c03bcb01e7" width="600" align="center"/>

In [2]:
import tensorflow as tf

print(tf.add([1, 3], [5, 7]))

a = tf.constant([1, 3], shape=[1, 2])
b = tf.constant([5, 7], shape=[2, 1])

print(tf.matmul(a, b))

Tensor("Add_1:0", shape=(2,), dtype=int32)
Tensor("MatMul_1:0", shape=(1, 1), dtype=int32)


In [3]:
import numpy as np

arr_1D = np.array([1, 2, 3, 4])
print(arr_1D.shape)

arr_2D = np.array([[1, 2], [3, 4]])
print(arr_2D.shape)

(4,)
(2, 2)


<img src="https://firebasestorage.googleapis.com/v0/b/deep-learning-crash-course.appspot.com/o/2Numpy3Dexplain.png?alt=media&token=acf5b8be-e917-4e42-b89a-0fbd9a335cfd" width="600" align="center"/>

In [4]:
arr_3D = np.array(   [   [[1, 2], [3, 4]]  ,  [[1, 2], [3, 4]]  ,  [[1, 2], [3, 4]]   ]   )
print(arr_3D.shape)

(3, 2, 2)


##  Numpy - Properties and Attributes

### <font color='Orange'> Numpy Attributes </font>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.ndim</span>** - Number of array dimensions</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.shape</span>** - Tuple of array dimensions</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.size</span>** - Number of elements in the array</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.dtype</span>** - Return the data type of an array’s elements</font>

In [5]:
import numpy as np

x = np.array(   [   [[1, 2], [3, 4]]  ,  [[1, 2], [3, 4]]  ,  [[1, 2], [3, 4]]   ]   )

print("The number of axis is", x.ndim)
print("The shape is", x.shape)
print("The size is", x.size)
print("The data type is", x.dtype)

The number of axis is 3
The shape is (3, 2, 2)
The size is 12
The data type is int32


In [6]:
y = x.astype('float')
print("The data type of x is", x.dtype)
print("The data type of y is", y.dtype)

The data type of x is int32
The data type of y is float64


<font size="3">**In Numpy, there are different mechanisms for creating arrays. This part will cover three commonly used methods for ndarray creation.**</font>

> <font size="3">**1. Converting Python sequences to Numpy arrays**</font>
<br>
> <font size="3">**2. Intrinsic Numpy array creation functions (e.g. arrange, ones, zeros, etc)**</font>
<br>
> <font size="3">**3. Replicating, joining, or mutating existing arrays**</font>

Reference: https://numpy.org/doc/stable/user/basics.creation.html

In [7]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
np.random.random(10)

array([0.12071531, 0.59468614, 0.40842723, 0.87135199, 0.95867503,
       0.79512017, 0.95792314, 0.35869723, 0.85744112, 0.74850962])

In [9]:
np.random.rand(10)

array([0.9499484 , 0.03816978, 0.25931498, 0.36851148, 0.55250631,
       0.52656679, 0.26171746, 0.57556141, 0.43403105, 0.56206205])

In [10]:
np.random.randint(10)

6

In [13]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [14]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<font size="3">**Numpy array can be indexed using the standard Python syntax <span style="background-color: #ECECEC; color:#0047bb">x[obj]</span>. There are two main types of indexing available:  basic slicing and advanced indexing.**</font>

### <font color='Orange'> Basic slicing </font>
> <font size="3">**Basic slicing extends Python’s basic concept of slicing to N dimensions. It occurs when <span style="background-color: #ECECEC; color:#0047bb">obj</span> is a slice object (constructed by start:stop:step notation inside of brackets), an integer, or a tuple of slice objects and integers.**</font>
<br>
### <font color='Orange'> Advanced Indexing </font>
> <font size="3">**Advanced indexing is triggered when the selection object, <span style="background-color: #ECECEC; color:#0047bb">obj</span>, is a non-tuple sequence object, an ndarray (of data type integer or bool), or a tuple with at least one sequence object or ndarray (of data type integer or bool). There are two types of advanced indexing: integer and boolean.**</font>

Reference: https://numpy.org/doc/stable/reference/arrays.indexing.html

In [20]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Positive Slicing without Step", x[1:7])
print("Positive Slicing with Step", x[1:7:2])

Positive Slicing without Step [1 2 3 4 5 6]
Positive Slicing with Step [1 3 5]


In [21]:
print("Negative Slicing without Step", x[-7:10])
print("Negative Slicing with Step", x[-7:10:2])

Negative Slicing without Step [3 4 5 6 7 8 9]
Negative Slicing with Step [3 5 7 9]


In [22]:
print("Positive Slicing by Default i", x[:7])
print("Positive Slicing by Default j", x[7:])
print("Positive Slicing by Default k", x[1:7])

Positive Slicing by Default i [0 1 2 3 4 5 6]
Positive Slicing by Default j [7 8 9]
Positive Slicing by Default k [1 2 3 4 5 6]


In [23]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

print(x)

print(x[0,0], x[1,1], x[2,0])

print(x[0][0], x[1][1], x[2][0])

print(x[[0, 1, 2], [0, 1, 0]], "   Remarks: this returns a list") 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0 4 6
0 4 6
[0 4 6]    Remarks: this returns a list


<font size="3">**An array has a shape given by the number of elements along each axis. The shape of an array can be changed with various commands, but the number of elements doesn't change.**</font>

><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.reshape</span>** - Gives a new shape to an array without changing its data.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.transpose</span>** - Reverse or permute the axes of an array; returns the modified array.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.vstack</span>** - Stack arrays in sequence vertically (row-wise).</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.hstack</span>** - Stack arrays in sequence horizontally (column-wise).</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.vsplit</span>** - Split an array into multiple sub-arrays vertically (row-wise).</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.hsplit</span>** - Split an array into multiple sub-arrays horizontally (column-wise).</font>
<br>

Reference: https://numpy.org/doc/stable/user/quickstart.html

In [27]:
# reshape

np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [29]:
np.arange(100).reshape(5,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [30]:
np.arange(100).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [31]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
y = np.reshape(x, (2,6))
z = np.reshape(x, (3,4))

print("The original shape of x is" , x.shape)
print("The original shape of y is" , y.shape)
print("The original shape of z is" , z.shape)

The original shape of x is (4, 3)
The original shape of y is (2, 6)
The original shape of z is (3, 4)


In [32]:
print("The tranpose of x is: \n" , np.transpose(x))

print("The tranpose of x is: \n" , np.transpose(x).shape)

The tranpose of x is: 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
The tranpose of x is: 
 (3, 4)


In [33]:
x = np.array([[0, 1, 2], [3, 4, 5]])
y = np.array([[6, 7, 8], [9, 10, 11]])

print(x, x.shape)
print(y, y.shape)

print("The result of horizontal stack: \n", np.hstack((x,y)), np.hstack((x,y)).shape)
print("The result of horizontal stack: \n", np.vstack((x,y)), np.vstack((x,y)).shape)

[[0 1 2]
 [3 4 5]] (2, 3)
[[ 6  7  8]
 [ 9 10 11]] (2, 3)
The result of horizontal stack: 
 [[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]] (2, 6)
The result of horizontal stack: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] (4, 3)


In [34]:
x = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])

print("The result of horizontal split: \n", np.hsplit(x, 2))
print(np.hsplit(x, 2)[0])
print(np.hsplit(x, 2)[1])

The result of horizontal split: 
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [35]:
print("The result of vectical split: \n", np.vsplit(x, 2))
print(np.vsplit(x, 2)[0])
print(np.vsplit(x, 2)[1])

The result of vectical split: 
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


### <font color='Orange'> Element-wise </font>
> <font size="3">**Numpy operations are usually done on pairs of arrays on an element-wise basis. In the simplest case, the two arrays must have exactly the same shape.**</font>


In [36]:
import numpy as np

x=np.array([1, 2, 3])
y=np.array([2, 2, 2])

print(x*y)

[2 4 6]


<font size="3">**Numpy has fast built-in aggregation and statistical functions for working on arrays, which includes:**</font>

><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.mean()</span>** - Compute the arithmetic mean along the specified axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.std()</span>** - Compute the standard deviation along the specified axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.var()</span>** - Compute the variance along the specified axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.sum()</span>** - Sum of array elements over a given axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.cumsum()</span>** - Return the cumulative sum of the elements along a given axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.cumprod()</span>** -  Return the cumulative product of elements along a given axis</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.min()</span>** - Return the minimum along a given axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.max()</span>** - Return the maximum along a given axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.argmin()</span>** - Returns the indices of the minimum values along an axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.argmax()</span>** - Returns the indices of the maximum values along an axis.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.all()</span>** - Test whether all array elements along a given axis evaluate to True.</font>
<br>
<br>
><font size="3">**<span style="background-color: #ECECEC; color:#0047bb">.any()</span>** - Test whether any array element along a given axis evaluates to True.</font>
<br>

Reference: https://www.pythonprogramming.in/numpy-aggregate-and-statistical-functions.html

In [38]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Mean:", np.mean(x))
print("Vertical Mean:", np.mean(x, axis=0))
print("Horizontal Mean:", np.mean(x, axis=1))

Mean: 3.5
Vertical Mean: [2.5 3.5 4.5]
Horizontal Mean: [2. 5.]


In [39]:
print("Standard Deviation:", np.std(x))
print("Vertical Standard Deviation:", np.std(x, axis=0))
print("Horizontal Standard Deviation:", np.std(x, axis=1))

Standard Deviation: 1.707825127659933
Vertical Standard Deviation: [1.5 1.5 1.5]
Horizontal Standard Deviation: [0.81649658 0.81649658]


In [40]:
print("Variance:", np.var(x))
print("Vertical Variance:", np.var(x, axis=0))
print("Horizontal Variance:", np.var(x, axis=1))

Variance: 2.9166666666666665
Vertical Variance: [2.25 2.25 2.25]
Horizontal Variance: [0.66666667 0.66666667]


In [41]:
print("Sum:", np.sum(x))
print("Vertical Sum:", np.sum(x, axis=0))
print("Horizontal Sum:", np.sum(x, axis=1))


Sum: 21
Vertical Sum: [5 7 9]
Horizontal Sum: [ 6 15]


In [42]:
print("Product:", np.prod(x))
print("Vertical Product:", np.prod(x, axis=0))
print("Horizontal Product:", np.prod(x, axis=1))

Product: 720
Vertical Product: [ 4 10 18]
Horizontal Product: [  6 120]


In [43]:
print(x)

print("Cumulative Sum:", np.cumsum(x))
print("Vertical Cumulative Sum:", np.cumsum(x, axis=0))
print("Horizontal Cumulative Sum:", np.cumsum(x, axis=1))

[[1 2 3]
 [4 5 6]]
Cumulative Sum: [ 1  3  6 10 15 21]
Vertical Cumulative Sum: [[1 2 3]
 [5 7 9]]
Horizontal Cumulative Sum: [[ 1  3  6]
 [ 4  9 15]]


In [44]:
print("Cumulative Product:", np.cumprod(x))
print("Vertical Cumulative Product:", np.cumprod(x, axis=0))
print("Horizontal Cumulative Product:", np.cumprod(x, axis=1))

Cumulative Product: [  1   2   6  24 120 720]
Vertical Cumulative Product: [[ 1  2  3]
 [ 4 10 18]]
Horizontal Cumulative Product: [[  1   2   6]
 [  4  20 120]]


In [45]:
print("Minimum:", np.min(x))
print("Vertical Minimum:", np.min(x, axis=0))
print("Horizontal Minimum:", np.min(x, axis=1))

Minimum: 1
Vertical Minimum: [1 2 3]
Horizontal Minimum: [1 4]


In [46]:
print("Maximum:", np.max(x))
print("Vertical Maximum:", np.max(x, axis=0))
print("Horizontal Maximum:", np.max(x, axis=1))

Maximum: 6
Vertical Maximum: [4 5 6]
Horizontal Maximum: [3 6]


In [47]:
print("Indices of minimum:" , np.argmin(x))
print("Indices of vertical minimum:" , np.argmin(x, axis=0))
print("Indices of horizontal minimum:" , np.argmin(x, axis=1))

Indices of minimum: 0
Indices of vertical minimum: [0 0 0]
Indices of horizontal minimum: [0 0]


In [48]:
print("Indices of maximum:" , np.argmax(x))
print("Indices of vertical maximum:" , np.argmax(x, axis=0))
print("Indices of horizontal maximum:" , np.argmax(x, axis=1))

Indices of maximum: 5
Indices of vertical maximum: [1 1 1]
Indices of horizontal maximum: [2 2]
